### ISSUE TITLE
[Error] Fail code=-3

### ISSUE THREAD

**Issue by DEV1L666** [MatthewPierson/1033-OTA-Downgrader#62] opened 2019-11-10 08:15 UTC
Hello, I'am having this issue. I'am running MacOS Mojave 10.14.6 and iPhone 5S (iPhone 6,2). Phone just stays black and when I boot it up again, it is the old iOS version. 
Here is the full error:

****RESTORING!****
Waiting for device to reconnect...
Version: 7e66824796f697ea54597dadbdba462382f004b9 - 247
Odysseus support: no
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket shsh/apnonce.shsh2 is done
Found device iPhone6,2 n53ap
[TSSC] opening manifests/BuildManifest_iPhone6,2_1033_OTA.plist
[TSSR] User specified not to request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set SEP+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening manifests/BuildManifest_iPhone6,2_1033_OTA.plist
[TSSR] User specified to request only a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
[Error] unsupported device mode, please put device in recovery mode or normal mode
[Error] Fail code=-3
Failed with errorcode=-3
Cleaning up :D
dummy_file
iBSS.iphone6.RELEASE.im4p
iBEC.iphone6.RELEASE.im4p
Mav7Mav8-7.60.00.Release.bbfw
sep-firmware.n53.RELEASE.im4p
ipsw/Firmware/aopfw.im4p
ipsw/Firmware/usr/local/standalone
ipsw/Firmware/usr/local
ipsw/Firmware/usr
ipsw/Firmware/dfu/iBEC.n69.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.n69u.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.n69.RELEASE.im4p
ipsw/Firmware/dfu/iBEC.n69u.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.n69u.RELEASE.im4p
ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.n69.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p.plist
ipsw/Firmware/dfu/iBSS.n69u.RELEASE.im4p
ipsw/Firmware/dfu/iBSS.n69.RELEASE.im4p
ipsw/Firmware/dfu
ipsw/Firmware/all_flash/DeviceTree.n51ap.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n51.RELEASE.im4p
ipsw/Firmware/all_flash/iBoot.n69u.RELEASE.im4p
ipsw/Firmware/all_flash/sep-firmware.n51.RELEASE.im4p.plist
ipsw/Firmware/all_flash/LLB.n69.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p
ipsw/Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p
ipsw/Firmware/all_flash/sep-firmware.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n69uap.im4p.plist
ipsw/Firmware/all_flash/LLB.iphone6.RELEASE.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n69uap.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p
ipsw/Firmware/all_flash/LLB.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/LLB.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/LLB.iphone6.RELEASE.im4p
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/iBoot.n69u.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/iBoot.iphone6.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n69.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/DeviceTree.n69ap.im4p.plist
ipsw/Firmware/all_flash/iBoot.n69.RELEASE.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n53.RELEASE.im4p.plist
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8003.im4p
ipsw/Firmware/all_flash/DeviceTree.n69ap.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p
ipsw/Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p
ipsw/Firmware/all_flash/iBoot.n69.RELEASE.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p
ipsw/Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n53ap.im4p
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/DeviceTree.n53ap.im4p.plist
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p
ipsw/Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/iBoot.iphone6.RELEASE.im4p
ipsw/Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p.plist
ipsw/Firmware/all_flash/sep-firmware.n53.RELEASE.im4p
ipsw/Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p.plist
ipsw/Firmware/all_flash/DeviceTree.n51ap.im4p
ipsw/Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/applelogo@2x~iphone.s8003.im4p.plist
ipsw/Firmware/all_flash/LLB.n69u.RELEASE.im4p
ipsw/Firmware/all_flash
ipsw/Firmware/Mav10-5.62.00.Release.plist
ipsw/Firmware/Mav7Mav8-7.60.00.Release.plist
ipsw/Firmware/Mav10-5.62.00.Release.bbfw
ipsw/Firmware/Mav7Mav8-7.60.00.Release.bbfw
ipsw/Firmware
ipsw/058-75381-062.dmg
ipsw/kernelcache.release.iphone8b
ipsw/058-74940-063.dmg
ipsw/Restore.plist
ipsw/kernelcache.release.iphone6
ipsw/BuildManifest.plist
ipsw/058-74917-062.dmg
ipsw/._058-74917-062.dmg
ipsw
If you see this, we're done! Shoutout to the devs and Matty for making this possible! - Merculous

**Comment by Merculous** [comment] 2019-11-18 01:13
Duplicate of #66

**Closed by Merculous** 2019-11-18 01:13 UTC
Labels: duplicate
